---

- name: Install Transmission
  dnf:
    name: transmission
    state: present

- name: Install Google Chrome
  dnf:
    name: google-chrome-stable
    state: present

- name: Install Microsoft Teams
  dnf:
    name: teams
    state: present
