---

- name: Install OpenJDK 1.8.0 and 11
  dnf:
    name:
      - java-1.8.0-openjdk-devel
      - java-11-openjdk-devel
    state: present

- name: Set java to preferred version
  alternatives:
    name: java
    link: /usr/bin/java
    path: /usr/lib/jvm/java-{{ preffered_java_ver }}-openjdk/bin/java

- name: Set javac to preferred version
  alternatives:
    name: javac
    link: /usr/bin/javac
    path: /usr/lib/jvm/java-{{ preffered_java_ver }}-openjdk/bin/javac

- name: Install OpenJFX 8 an latest
  dnf:
    name:
      - openjfx8
      - openjfx
    state: present

- name: Install Svetovid library
  dnf:
    name: svetovid-lib
    state: present

- name: Add Svetovid to classpath
  lineinfile:
    path: /etc/environment
    line: CLASSPATH="/usr/share/java/svetovid-lib/svetovid-lib.jar"

- name: Install Geany
  dnf:
    name: geany
    state: present

- name: Install Eclipse
  dnf:
    name: eclipse
    state: present

- name: Install Bouml and Qt4 for Bouml
  dnf:
    name:
      - Qt4LibsForBouml
      - bouml
    stage: present
