---

- name: Add Dušan's repo
  yum_repository:
    name: dusan
    description: Dušan's repo of various packages
    baseurl: https://repos.dusansimic.me/rpms
    gpgcheck: yes
    gpgkey: https://repos.dusansimic.me/key.gpg

- name: Update packages
  dnf:
    name: "*"
    state: latest

- name: Install development tools
  include: devel.yaml
