---

- name: Set up repos
  include: repos.yml

- name: Update packages
  dnf:
    name: "*"
    state: latest
  tags: base

- name: Install development tools
  include: devel.yml
  tags: devel

- name: Install apps
  include: apps.yml
  tags: extra
